### PR TITLE
Added README.md

### PR DESCRIPTION
**Pull request by KrauseFx**
Added the documentation of the Fastfile :+1:

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks!

Still need to work a few things out in my main readme. I need access to the Github API token for both steps, and travis doesnt have a good solution for a running a release step after a build matrix has passed :(

**Comment by KrauseFx** [comment]
@kcharwood the latest release of `fastlane` will automatically generate the docs every time you run fastlane. So it should be good enough to just generate it locally and push it from there.

**Comment by kcharwood** [comment]
Didn't mean for this issue :)

Was just giving you an update on the entire project and things I still need to iron out... Figured you would be interested :rocket:

**Comment by KrauseFx** [comment]
:+1:

**Pull request merged**
